os: linux
sudo: false
language: go

go:
  - 1.6.4
  - 1.7.6
  - 1.8.3
  - tip

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master

addons:
  apt:
    packages:
    - libnotify-dev
    - libgtk2.0-dev

install: go get -t -v

script: go test -v

notifications:
  email:
    on_success: always
